name: Deploy Prod Parser

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install App Dependencies
        run: npm ci

      - name: Create env file
        run: |
          echo "${{ secrets.ENV_FILE_PROD }}" > .env

      - name: Build Nest Application
        run: npm run build

      - name: Deploy Application to Server
        uses: appleboy/scp-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          target: /home/${{ secrets.SERVER_USER }}/fxql-parser
          source: |
            dist/
            node_modules/
            .env
            package.json
            pm2.config.json

      - name: Run Remote Commands via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          script: |
            cd /home/${{ secrets.SERVER_USER }}/fxql-parser
            npm run migration:run
            if pm2 describe fxql-parser > /dev/null; then pm2 delete fxql-parser; fi
            pm2 start pm2.config.json
