name: Deploy Prod Parser

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Deploy
    runs-on: [parser]

    steps:
      - uses: actions/checkout@v4

      - name: Install App Dependencies
        run: npm ci

      - name: Create env file
        run: |
          echo "${{ secrets.ENV_FILE_PROD }}" > .env

      - name: Build Nest Application
        run: NODE_OPTIONS=--max-old-space-size=2048 npm run build

      - name: Start PM2
        run: |
          if pm2 describe fxql-parser > /dev/null; then pm2 delete fxql-parser; fi
          npm run migration:run && pm2 start pm2.config.json
